chore: checkpoint

diff --git a/.github/workflows/configure_app.yml b/.github/workflows/configure_app.yml
--- a/.github/workflows/configure_app.yml
+++ b/.github/workflows/configure_app.yml
@@ -74,7 +74,7 @@ jobs:
       # There is no API for this yet, so we just use curl
       # to verify that the page link contains a link to the app
       - name: "Check Repository Page: https://${{ env.ORGNAME }}.github.io/App"
-        run: curl --location --fail -s "${{ env.ORGNAME }}.github.io/App" | grep "https://appfair.app/fair?app=${{ env.ORGNAME }}"
+        run: (curl --location --fail -s "${{ env.ORGNAME }}.github.io/App" | grep "https://appfair.app/fair?app=${{ env.ORGNAME }}") || (sleep 120 && (curl --location --fail -s "${{ env.ORGNAME }}.github.io/App" | grep "https://appfair.app/fair?app=${{ env.ORGNAME }}"))
 
       - name: "Checkout ${{ env.PRODUCT_NAME }}"
         uses: actions/checkout@v2
