chore: checkpoint

diff --git a/.github/workflows/fork_apply.yml b/.github/workflows/fork_apply.yml
--- a/.github/workflows/fork_apply.yml
+++ b/.github/workflows/fork_apply.yml
@@ -220,12 +220,38 @@ jobs:
         run: |
           echo "Uploading release assets: ${GITHUB_REF#refs/tags/}"
           # create a pre-release if it doesn't already exist 
-          gh release create "${GITHUB_REF#refs/tags/}" --prerelease || true
+          # TODO: --prerelease ?
+          gh release create "${GITHUB_REF#refs/tags/}" || true
+
           # upload staging assets to the existing GitHub release
           gh release upload "${GITHUB_REF#refs/tags/}" -- staging/*.*
-          # create a PR with the correct bundle info
-          git stash || true
-          git checkout main
-          git status
-          gh pr create --no-maintainer-edit --repo "${{ inputs.fairground }}/App" --title "${{ env.BUNDLE_ID }} ${GITHUB_REF#refs/tags/}" --body "${{ env.BUNDLE_ID }} release ${GITHUB_REF#refs/tags/}"
+
+          # ideally, we would automatically create the 
+          # integrate-release pull request here, but tying to 
+          # create one raises the error:
+          #
+          # "pull request create failed: GraphQL error: Resource not accessible by integration"
+          #
+          # This is because forked repositories only have read access:
+          #
+          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
+          #
+          # We cannot use "Send write tokens to workflows from pull requests"
+          # due to it being restricted to private repositories:
+          #
+          # https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks
+          #
+          # Another alternative could be to require the forked user to 
+          # set up a PAT with write permission, but that's a big ask.
+          #
+          # So for now, we just require the user to open a PR
+          # manually and set its title correctly.
+          #
+          # For more information, see:
+          # https://github.community/t/github-actions-are-severely-limited-on-prs/18179
+
+          # git stash || true # ensure that local changes (e.g., the icon) are discarded
+          # git checkout main # ensure we are on main
+          # git status
+          # gh pr create --no-maintainer-edit --repo "${{ inputs.fairground }}/App" --title "${{ env.BUNDLE_ID }} ${GITHUB_REF#refs/tags/}" --body "${{ env.BUNDLE_ID }} release ${GITHUB_REF#refs/tags/}"
 
