chore: checkpoint

diff --git a/.github/workflows/fork_apply.yml b/.github/workflows/fork_apply.yml
--- a/.github/workflows/fork_apply.yml
+++ b/.github/workflows/fork_apply.yml
@@ -114,7 +114,19 @@ jobs:
         run: xcrun swift run -- fairtool validate --verbose true --hub "github.com/${{ inputs.fairground }}" --org "${{ env.ORGNAME }}" --token "${{ secrets.GITHUB_TOKEN }}" --project . --output -
 
       - name: "Generate Icon"
-        run: xcrun swift run -- fairtool icon --org "${{ env.ORGNAME }}" --accent-color "Assets.xcassets/AccentColor.colorset/Contents.json" --output Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png --output Assets.xcassets/AppIcon.appiconset/AppIcon-512.png || true # tolerate failure
+        run: |
+          xcrun swift run -- fairtool icon --org "${{ env.ORGNAME }}" \
+            --accent-color Assets.xcassets/AccentColor.colorset/Contents.json \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-32.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-76.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-120.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-180.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-152.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-167.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-256.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-512.png \
+            --output Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png \
+              || true # tolerate failure
 
       - name: "Test Swift Package"
         if: false # needs macOS 12 # github.event_name == 'push' # only run tests in forks
